export const keyDescriptions: Record<string, string> = {
  WO_NO: "رقم الاوردر",
  JO_NO: "رقم الحوض",
  CLIENT_REF: "مرجع العميل",
  ITEM_CODE: "كود الصنف",
  ROLL_BARCODE: "باركود الرول",
  ACT_DATA_08: "اللون",
  ACT_DATA_09: "المقاس",
  ACT_DATA_07: "الاستايل",
};

export const DEFECT_LABELS: Record<string, string> = {
  DEFECT_01: "خروم",
  DEFECT_02: "وقعات",
  DEFECT_03: "وصلات",
  DEFECT_04: "تساقيط نسيج",
  DEFECT_05: "ريجة عرضية",
  DEFECT_06: "شعيرات غريبه",
  DEFECT_07: "ابر نسيج",
  DEFECT_08: "ريجه طولية",
  DEFECT_09: "مناطق رفيعه",
  DEFECT_10: "مناطق سميكه",
  DEFECT_11: "بقع وخطوط زيت",
  DEFECT_12: "تقطيع ليكر",
  DEFECT_13: "طول غرزة",
  DEFECT_14: "مظهرية القماش",
  DEFECT_15: "عدد ابر مختلف",
  DEFECT_16: "اخنلاف لوط",
  DEFECT_17: "اختلاف نمرة الخيط",
  DEFECT_18: "خط بقع زيت بطول التوب",
  DEFECT_19: "ريجة طولية بطول التوب",
  DEFECT_20: "ريجة عرضية",
};
export const DYE_DEFECT_LABELS: Record<string, string> = {
  DYE_DEFECT_01: "خروم",
  DYE_DEFECT_02: "الوصلات",
  DYE_DEFECT_03: "تنتيش -عقد",
  DYE_DEFECT_04: "عيوب الليكرا",
  DYE_DEFECT_05: "الاتساخات",
  DYE_DEFECT_06: "بقع الصباغه",
  DYE_DEFECT_07: "عيوب الغزل",
  DYE_DEFECT_08: "تساقيط وابره مكسوره",
  DYE_DEFECT_09: "خط ابيض",
  DYE_DEFECT_10: "مناطق رفيعه",
  DYE_DEFECT_11: "مناطق سميكه",
  DYE_DEFECT_12: "إحتكاك",
  DYE_DEFECT_13: "بقع وخطوط زيت",
  DYE_DEFECT_14: "كسرات",
  DYE_DEFECT_15: "مستوى صباغة و درجات لون",
  DYE_DEFECT_16: "التطرية",
  DYE_DEFECT_17: "ريجه طوليه",
  DYE_DEFECT_18: "كسرة التوب الخام",
  DYE_DEFECT_19: "ريجه عرضيه",
  DYE_DEFECT_20: "درجة اللون",
  DYE_DEFECT_21: "مظهرية",
  DYE_DEFECT_22: "خطوط غزل عرضية",
  DYE_DEFECT_23: "شعيرات غزل غريبة",
  DYE_DEFECT_24: "ابرة نسيج بطول التوب",
};
